package gouringasm

type IoUringOpcode = int32
type IoUringSetupFlag = __u32

const (
	IORING_SETUP_IOPOLL     IoUringSetupFlag = (1 << 0) /* io_context is polled */
	IORING_SETUP_SQPOLL     IoUringSetupFlag = (1 << 1) /* SQ poll thread */
	IORING_SETUP_SQ_AFF     IoUringSetupFlag = (1 << 2) /* sq_thread_cpu is valid */
	IORING_SETUP_CQSIZE     IoUringSetupFlag = (1 << 3) /* app defines CQ size */
	IORING_SETUP_CLAMP      IoUringSetupFlag = (1 << 4) /* clamp SQ/CQ ring sizes */
	IORING_SETUP_ATTACH_WQ  IoUringSetupFlag = (1 << 5) /* attach to existing wq */
	IORING_SETUP_R_DISABLED IoUringSetupFlag = (1 << 6) /* start with ring disabled */
	IORING_SETUP_SUBMIT_ALL IoUringSetupFlag = (1 << 7) /* continue submit on error */
)

const (
	IORING_OP_NOP IoUringOpcode = iota
	IORING_OP_READV
	IORING_OP_WRITEV
	IORING_OP_FSYNC
	IORING_OP_READ_FIXED
	IORING_OP_WRITE_FIXED
	IORING_OP_POLL_ADD
	IORING_OP_POLL_REMOVE
	IORING_OP_SYNC_FILE_RANGE
	IORING_OP_SENDMSG
	IORING_OP_RECVMSG
	IORING_OP_TIMEOUT
	IORING_OP_TIMEOUT_REMOVE
	IORING_OP_ACCEPT
	IORING_OP_ASYNC_CANCEL
	IORING_OP_LINK_TIMEOUT
	IORING_OP_CONNECT
	IORING_OP_FALLOCATE
	IORING_OP_OPENAT
	IORING_OP_CLOSE
	IORING_OP_FILES_UPDATE
	IORING_OP_STATX
	IORING_OP_READ
	IORING_OP_WRITE
	IORING_OP_FADVISE
	IORING_OP_MADVISE
	IORING_OP_SEND
	IORING_OP_RECV
	IORING_OP_OPENAT2
	IORING_OP_EPOLL_CTL
	IORING_OP_SPLICE
	IORING_OP_PROVIDE_BUFFERS
	IORING_OP_REMOVE_BUFFERS
	IORING_OP_TEE
	IORING_OP_SHUTDOWN
	IORING_OP_RENAMEAT
	IORING_OP_UNLINKAT
	IORING_OP_MKDIRAT
	IORING_OP_SYMLINKAT
	IORING_OP_LINKAT
	IORING_OP_MSG_RING
	IORING_OP_FSETXATTR
	IORING_OP_SETXATTR
	IORING_OP_FGETXATTR
	IORING_OP_GETXATTR
	IORING_OP_SOCKET
	IORING_OP_URING_CMD

	/* this goes last obviously */
	IORING_OP_LAST
)
